### ISSUE TITLE
Include IlmImf and Zlib sources in openexr-sys if possible

### ISSUE THREAD

**Issue by tgiddings** [cessen/openexr-rs#29]
Including library sources when licenses allow in -sys packages makes -sys packages a lot more convenient to use. As far as I can tell, the Zlib license and modified BSD license are both compatible with the MIT license.

IlmImf alone nearly breaks the normal 10MB limit for crates.io, but supposedly you can ask to have a higher limit for a specific crate if necessary, up to 50MB rust-lang/crates.io#40.

**Comment by cessen** [comment]
@tgiddings 
Sorry for the late response!

I'm not really inclined to include these directly in the crate.  zlib could make sense, since it's pretty simple.  But for the OpenEXR deps themselves my reasoning is:

1. They aren't always trivial to get building on different platforms.
2. I therefore wouldn't be confident that any build scripts we put together would reliably build them on platforms I can't test on.
3. Therefore, I would worry about difficult-to-diagnose errors for end-users of the crate.
4. Finally, therefore, I would prefer to directly expose that complexity to the user, so it's at least not as confusing or difficult to diagnose when things go wrong.

So my general leaning is to keep them out-of-tree for now, and leave it up to the consumers of the crate to handle it.
