### ISSUE TITLE
Is it time to release 0.7.0 to crates.io?

### ISSUE THREAD

**Issue by norru** [cessen/openexr-rs#41]
I am currently linking openexr-rs from GitHub repositories as they contain latest updates.

Since 0.6.0 there have been significant changes:

- data window fixes (crash bug)
- exception message management fixes (crash/corruption bug)
- set_global_thread_count() (enhancement)
- set_multiview() (enhancement)

For consistency I would be happier to use `crates.io` repo instead.

**Comment by Ralith** [comment]
I'm not sure we've actually made any *breaking* changes? Guess it doesn't hurt to play it safe.

**Comment by norru** [comment]
There are no *breaking changes* but the API has been *extended*.

> Semantic Versioning 2.0.0
> Given a version number MAJOR.MINOR.PATCH, increment the:

>    MAJOR version when you make incompatible API changes,
>    MINOR version when you add functionality in a backwards-compatible manner, and
>    PATCH version when you make backwards-compatible bug fixes.

From https://semver.org/

Now, this is a still a 0.x so it's ok to play loose, as long as it doesn't cause confusion. As a library user I'd rather expect new functionality to trigger a MINOR increment.

**Comment by Ralith** [comment]
In the Rust ecosystem, and in particular in cargo, pre-1.0 versions are
treated as a right shift; minor versions have the semantics of major, and
patch of minor.

**Comment by norru** [comment]
Fair enough. I've seen this in many other projects, still find it confusing sometimes as any MINOR version triggers a PATCH (what triggers a PATCH then?) :)

Anyway, I have no strong opinion on this. Either way is fine.

**Comment by cessen** [comment]
I think it is definitely time for a new release, yes!  I've been thinking about that too, actually.  I'll take care of it this coming weekend.

As for 0.6.1 vs 0.7.0 , for some reason 0.7.0 feels more right to me, but I have zero actual rationale for that.  In the end, I don't really care one way or the other, and I suspect doesn't really matter _that_ much...?  If anyone feels strongly one way or the other, let me know.  Otherwise I'll probably just do 0.7.0.

**Comment by cessen** [comment]
Done!

0.7.0 is live on crates.io
